config/routes.rb
CloudLeagues::Application.routes.draw do
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', as: :logout
  resource :password_resets, except: [:show]

  resources :users do
    resource :account_information, as: :profile, path: :profile
    resources :chat_messages, only: [:index, :show, :new, :create, :destroy]
  end

  resources :tournaments do
    resources :waiting_players, only: [:create, :update, :destroy], path: :players
    resources :matches, only: [:index, :show, :edit, :update] do
      resources :match_player_relations, only: [:update]
    end
  end

  resources :maps

  resources :feedbacks, only: [:create]

  root to: 'home#index'
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  # Leagues
  ALL = 0b1111111
  GRAND_MASTER = 0b1000000
  MASTER = 0b0100000
  DIAMOND = 0b0010000
  PLATINUM = 0b0001000
  GOLD = 0b0000100
  SILVER = 0b0000010
  BRONZE = 0b0000001

  LEAGUES = {
    ALL => I18n.t('tournament.leagues.all'),
    GRAND_MASTER => I18n.t('tournament.leagues.grand_master'),
    MASTER => I18n.t('tournament.leagues.master'),
    DIAMOND => I18n.t('tournament.leagues.diamond'),
    PLATINUM => I18n.t('tournament.leagues.platinum'),
    GOLD => I18n.t('tournament.leagues.gold'),
    SILVER => I18n.t('tournament.leagues.silver'),
    BRONZE => I18n.t('tournament.leagues.bronze')
  }

  # Associations
  has_many :waiting_players, dependent: :destroy
  has_many :matches, dependent: :destroy
  has_many :games, through: :matches
  has_many :map_lists, order: 'map_order ASC', dependent: :destroy
  has_many :maps, through: :map_lists
  
  # Validations
  validates :league, presence: true, inclusion: { in: 1..127 }
  validates :max_players, presence: true, inclusion: { in: 2..64 }
  validates :name, presence: true, uniqueness: true, length: { within: 5..25 }
  validates :prize, presence: true, inclusion: { in: 0..4999 }
  validates :default_best_of, presence: true, inclusion: { in: [1, 3, 5, 7, 9, 11] }
  validate :validate_waiting_players
  validate :validate_type
  validate :validate_times
  validate :validate_map_list

  # Callbacks
  before_validation :strip_inputs
  after_create :create_structure
  after_update :update_structure

  # Attribute Whitelists
  attr_accessible :league, :type, :start_time, :registration_time, :max_players, :name, :map_lists_attributes, :default_best_of, as: :moderator
  attr_accessible :league, :type, :start_time, :registration_time, :max_players, :name, :prize, :map_lists_attributes, :default_best_of, as: :admin

  # Nested Attributes
  accepts_nested_attributes_for :map_lists, allow_destroy: true, reject_if: lambda { |a| a[:map_id].blank? }

  def started?
    Time.now >= start_time
  end

  def open_spots
    [0, max_players - waiting_players.where(player_accepted: true).count].max
  end

  def starting_matches
    match_list = matches
    start_matches = matches
    
    match_list.each do |match|
      match.match_links.each do |match_link|
        start_matches = start_matches.where("id != ?", match_link.next_match_id)
      end
    end
    
    start_matches
  end

  protected
  def strip_inputs
    name.strip! if name
  end

  def create_structure
    raise ActiveRecord::Rollback unless self.becomes(type.constantize).create_structure
  end

  # Updating tournaments is a fairly complicated process because of the implications 
  # involved in updating some of the attributes. I have decided to take a fairly strict
  # approach to updating tournaments for the following reasons:
  # 1) The most important aspect of any website is the user experience. I do not want to
  #    have any unexpected behavior (e.g. randomly dropping players from tournaments).
  # 2) Tournament admins should be responsible. They shouldn't have to update something
  #    like start time after the tournament has already started.
  # 3) Allowing tournament modification after a tournament has started leads to an
  #    extremely large number of edge cases. It doesn't make sense to try and handle
  #    these all.
  def update_structure
    # Check for errors.
    errors.add :type, I18n.t('activerecord.errors.models.tournament.attributes.type.changed') if type_changed?
    errors.add :start_time, I18n.t('activerecord.errors.models.tournament.attributes.start_time.changed') if start_time_changed? and start_time_was <= Time.now
    
    if started?
      errors.add :league, I18n.t('activerecord.errors.models.tournament.attributes.started.league') if league_changed?
      errors.add :start_time, I18n.t('activerecord.errors.models.tournament.attributes.started.start_time') if start_time_changed?
      errors.add :max_players, I18n.t('activerecord.errors.models.tournament.attributes.started.max_players') if max_players_changed?
      errors.add :registration_time, I18n.t('activerecord.errors.models.tournament.attributes.started.registration_time') if registration_time_changed?
    end

    if locked?
      errors.add :league, I18n.t('activerecord.errors.models.tournament.attributes.locked.league') if league_changed?
      errors.add :start_time, I18n.t('activerecord.errors.models.tournament.attributes.locked.start_time') if start_time_changed?
      errors.add :max_players, I18n.t('activerecord.errors.models.tournament.attributes.locked.max_players') if max_players_changed?
      errors.add :registration_time, I18n.t('activerecord.errors.models.tournament.attributes.locked.registration_time') if registration_time_changed?
    end

    raise ActiveRecord::Rollback unless errors.empty?
    
    if max_players_changed?
      destroy_structure
      reload
      create_structure
      waiting_players.where(player_accepted: true).each { |player| add_player(player) }
    end
  end

  def destroy_structure
    matches.each { |match| match.destroy }
  end

  def validate_waiting_players
    return if league.nil?
    accepted_count = 0
    all_players_belong = true

    waiting_players.each do |player| 
      accepted_count += 1 if player.player_accepted
      all_players_belong = false if ((player.user.account_information.league & league) == 0)
    end
    
    errors.add(:waiting_players, I18n.t('activerecord.errors.models.tournament.attributes.waiting_players.too_many')) if accepted_count > (max_players || 0)
    errors.add(:waiting_players, I18n.t('activerecord.errors.models.tournament.attributes.waiting_players.dont_belong')) unless all_players_belong
  end

  def validate_type
    errors.add(:type, I18n.t('activerecord.errors.models.tournament.attributes.type.blank')) and return if type.nil?
    errors.add(:type, I18n.t('activerecord.errors.models.tournament.attributes.type.changed')) if !new_record? and type_changed?
    tournament_file_names = Dir.glob('app/models/*_tournament.rb').map do |file_name|
      File.basename file_name, '.rb'
    end

    class_names = tournament_file_names.map do |file_name|
      file_name.split('_').map { |w| w.capitalize }.join
    end

    errors.add(:type, I18n.t('activerecord.errors.models.tournament.attributes.type.inclusion')) unless class_names.include?(type)
  end
  
  def validate_times
    errors.add(:start_time, I18n.t('activerecord.errors.models.tournament.attributes.start_time.blank')) and return if start_time.nil?
    errors.add(:start_time, I18n.t('activerecord.errors.models.tournament.attributes.start_time.future')) and return if new_record? and start_time <= Time.now
    errors.add(:registration_time, I18n.t('activerecord.errors.models.tournament.attributes.registration_time.blank')) and return if registration_time.nil?
    errors.add(:registration_time, I18n.t('activerecord.errors.models.tournament.attributes.registration_time.too_late')) and return if registration_time >= start_time
  end

  def validate_map_list
    errors.add :map_lists, I18n.t('activerecord.errors.models.tournament.attributes.map_lists.order') if map_lists.select { |ml| ml.map_order == 1 }.empty?
  end
end

app/models/tournaments/single_elimination_tournament.rb
class SingleEliminationTournament < Tournament
  def create_structure
    closest_power = Math.log2(max_players).ceil
    true_max_players = 2 ** closest_power
    
    match_list = []
    for match_level in 0..(closest_power - 1)
      match_list[match_level] = Array.new(true_max_players / (2 ** (match_level + 1)))
      
      for i in 0..(match_list[match_level].length - 1)
        new_match = self.matches.build
        new_match.save ? match_list[match_level][i] = new_match : self.destroy
        
        if match_level != 0
          first_link = match_list[match_level - 1][2 * i].winner_match_links.build
          first_link.next_match_id = match_list[match_level][i].id
          
          second_link = match_list[match_level - 1][2 * i + 1].winner_match_links.build
          second_link.next_match_id = match_list[match_level][i].id
          
          self.destroy unless first_link.save && second_link.save
        end
      end
    end
  end

  def destroy_structure
    matches.each { |match| match.destroy }
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_filter :authenticate, except: [:index, :show]
  load_and_authorize_resource

  def index
    @tournaments = Tournament.find :all
  end

  def show
    if current_user
      @waiting_player = current_user.waiting_players.where(tournament_id: @tournament.id).first
    end
  end
    
  def new
    @tournament = Tournament.new
    (1..3).each { |i| @tournament.map_lists.build.map_order = i }
  end

  def create
    if params[:tournament] && params[:tournament][:league].is_a?(Hash)
      league = 0b0
      league_flags = params[:tournament][:league] || {}
      
      league_flags.keys.each do |key|
        league = league | key.to_i if league_flags[key].to_i == 1
      end

      params[:tournament][:league] = league
    end

    @tournament = Tournament.new params[:tournament], as: current_user.role

    if @tournament.save
      redirect_to tournament_path(@tournament)
    else
      (1..3).each { |i| @tournament.map_lists.build.map_order = i } if @tournament.map_lists.empty?
      render action: :new
    end
  end

  def edit
  end

  def update
    if params[:tournament] && params[:tournament][:league].is_a?(Hash)
      league = 0b0
      league_flags = params[:tournament][:league] || {}
      
      league_flags.keys.each do |key|
        league = league | key.to_i if league_flags[key].to_i == 1
      end
      
      params[:tournament][:league] = league
    end

    if @tournament.update_attributes params[:tournament], as: current_user.role
      flash[:notice] = 'Tournament updated successfully.'
      
      respond_to do |format|
        format.html { redirect_to tournament_path(@tournament) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render action: :edit }
        format.js { render json: @tournament.errors.to_json }
      end
    end
  end

  def destroy
    flash[:notice] = 'Tournament destroyed successfully.'
    @tournament.destroy
    redirect_to tournaments_path
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def new_player(tournament, user)
    new_player = tournament.waiting_players.build
    new_player.user_id = user.id if user
    tournament.waiting_players.delete new_player
    new_player
  end

  def to_time_remaining(tournament_start_time)
    secs_remaining = (tournament_start_time - Time.now).to_i
    neg_flag = secs_remaining < 0 ? ' ago' : ''
    secs_remaining = secs_remaining.abs

    mins_remaining = secs_remaining / 60
    hours_remaining = mins_remaining / 60
    days_remaining = hours_remaining / 24

    if days_remaining > 0 
      "#{days_remaining}d#{neg_flag}"
    elsif hours_remaining > 0
      "#{hours_remaining}h#{neg_flag}"
    elsif mins_remaining > 0
      "#{mins_remaining}m#{neg_flag}"
    else secs_remaining >= 0
      "< 1m#{neg_flag}"
    end
  end

  def image_for_league(league_id)
    "#{Tournament::LEAGUES[league_id].gsub(/ /, '_').underscore}.png"
  end

  def match_levels(tournament)
    num_levels = Math.log2(tournament.max_players).ceil
    levels = []
    
    levels.push tournament.starting_matches
    last_levels = levels[0]
    
    (num_levels - 1).times do 
      new_levels = last_levels.map do |match|
        match.match_links.map do |ml|
          Match.find ml.next_match_id
        end
      end

      new_levels.flatten!
      new_levels = new_levels | new_levels
      levels.push new_levels
      last_levels = new_levels
    end

    levels
  end

  def current_match(tournament, player)
    match = player.match_player_relations.first.match
    
    while match.winner_id && match.winner_id == player.id && !match.winner_match_links.empty?
      match = Match.find(match.winner_match_links.first.next_match_id)
    end

    match
  end
end

app/views/tournaments/_column_names.html.erb
<div class="tournamentColumnNames">
  <div class="tournamentAttribute tournamentStartTime">Starts In</div>
  <div class="tournamentAttribute tournamentOpenSpots">Open Spots</div>
  <div class="tournamentAttribute tournamentPrize">Prize Pool</div>
  <div class="tournamentAttribute tournamentName">Name</div>
</div>

app/views/tournaments/_league_index.html.erb
<%
   league ||= Tournament::ALL
%>
<% if league == Tournament::ALL %>
  <% tournaments = Tournament.where("league = ? AND registration_time < ?", Tournament::ALL, Time.now).order("start_time DESC").limit(5) %>
<% else %>
  <% tournaments = Tournament.where("league & ? > 0 AND league != ? AND registration_time < ?", league, Tournament::ALL, Time.now).order("start_time DESC").limit(5) %>
<% end %>

<% tournament_count = 0 %>
<% tournaments.each do |tournament| %>
  <% tournament_count += 1 %>
  <div class="tournamentRow <%= tournament_count % 2 == 0 ? "lightRow" : "darkRow" %>">
    <% start_time = tournament.start_time < Time.now ? "X" : to_time_remaining(tournament.start_time) %>
    <div class="tournamentAttribute tournamentStartTime"><%= start_time %></div>
    <div class="tournamentAttribute tournamentOpenSpots"><%= tournament.open_spots %></div>
    <div class="tournamentAttribute tournamentPrize">$<%= tournament.prize %></div>
    <div class="tournamentAttribute tournamentName"><%= link_to tournament.name, tournament_path(tournament) %></div>
  </div>
<% end %>

<% if tournaments.empty? %>
  <div class="noTournamentsMessage">
    There are no recent tournaments in this category.
  </div>
<% end %>

app/views/tournaments/_player_actions.html.erb
<div class="tournamentPanel" id="playerActions">
  <h2>Player Actions</h2>

  <% if !@waiting_player.player_accepted %>
    <p>You are on the waiting list. You have no available actions.</p>
  <% elsif !@tournament.started? %>
    <p>You are currently registered for this tournament. You will be able to use this section once the tournament starts.</p>
  <% else %>
    <%= javascript_include_tag "cloud_chat_client.js" %>

    <% match = current_match(@tournament, @waiting_player) %>
    <% player_relation = match.match_player_relations.where(waiting_player_id: @waiting_player.id).first %>
    <% other_relation = match.match_player_relations.where("waiting_player_id != ?", @waiting_player.id).first %>
    <% game = match.games.last %>

    <table id="matchInfo">
      <tr style="font-weight: bold;">
	<td><p style="padding-left: 15px;">Current Match</p></td>
	<td style="text-align: center;"><p>Score</p></td>
	<td style="text-align: right;"><p style="padding-right: 15px;">Best Of</p></td>
      </tr>
      <tr>
	<% other_player = other_relation.nil? ? "N/A" : other_relation.waiting_player.user.login %>
	<% other_wins = other_relation.nil? ? 0 : match.games.where(winner_id: other_relation.waiting_player.id).count %>
	<td><p style="padding-left: 15px;"><%= @waiting_player.user.login %> vs. <%= other_player %></p></td>
	<td style="text-align: center;"><p>You: <%= match.games.where(winner_id: @waiting_player.id).count %> | Opponent: <%= other_wins %></p></td>
	<td style="text-align: right;"><p style="padding-right: 30px;"><%= match.best_of %></p></td>
      </tr>
    </table>

    <div id="matchInfoActionContainer">
      <div id="matchChatContainer">
	<% if !other_relation.nil? && match.winner_id.nil?%>
	  <% sender = other_relation.waiting_player.user.chat_profile %>
	  <% recipient = @waiting_player.user.chat_profile %>
	  <% messages = ChatMessage.where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', sender.chat_id, recipient.chat_id, recipient.chat_id, sender.chat_id).order('id DESC').limit(25) %>
	  <% messages = messages.to_a.sort %>

	  <table id="chatAndMapTable" cellspacing="0" cellpadding="0">
	    <tr>
	      <td class="chatColumn" style="font-weight: bold; text-align: center;">Chat with Opponent</td>
	      <td class="mapColumn">Current Map</td>
	    </tr>

	    <tr>
	      <td class="chatColumn">
		<div id="matchChat">
		  <% messages.each do |message| %>
		    <% name = message.sender_id == sender.chat_id ? sender.user.login : "You" %>
		    <p class="chatMessage oldMessage"><b><%= name %>:</b> <%= message.message %></p>
		    <% message.update_column :read, true if !message.read && message.recipient_id == recipient.chat_id %>
		  <% end %>
		</div>
	      </td>
	      <td class="mapColumn">
		<% map_name = "" %>
		<% if match.games.count == 1 %>
		  <% map_num = match.previous_matches.length % match.tournament.map_lists.count %>
		  <% map = match.tournament.map_lists[map_num].map %>
		  <% map_name = map.name %>
		  <%= image_tag map.image.url(:small) %>
	        <% else %>
		  <% map_name = "Loser's Pick" %>
		  <%= image_tag "loser_pick.png" %>
		<% end %>
	      </td>
	    </tr>

	    <tr>
	      <td class="chatColumn">
		<%= form_tag "javascript:void(0)", id: "chatMessageForm", autocomplete: "off" do %>
		  <%= hidden_field_tag :recipient_id, other_relation.waiting_player.user.chat_profile.chat_id %>
		  <%= text_field_tag :message, "", id: "chatMessageInput" %><%= submit_tag "Send", id: "chatMessageSubmit" %>
		<% end %>
	      </td>
	      <td class="mapColumn"><%= map_name %></td>
	    </tr>
	  </table>
	<% elsif match.winner_id.nil? && match.bye? %>
	  <div class="noChatMessage">This match is a bye.</div> 
	<% elsif match.winner_id.nil? %>
	  <div class="noChatMessage">Waiting for other player to join.</div>
	<% elsif match.winner_id == @waiting_player.id %>
	  <div class="noChatMessage">Congratulations, you won!</div>
	<% else %>
	  <div class="noChatMessage">Sorry! You lost :(</div>
	<% end %>
      </div>
      
      <div id="matchActionContainer">
	<% if player_relation.accepted && !match.contested? && match.winner_id.nil? %>
	  <div class="actionButton disabledAction">Match Accepted</div>

	  <% both_accepted = match.match_player_relations.where(accepted: true).count == 2 %>
	  <% if match.bye? || both_accepted && match.winner_id.nil? %>
	    <%= form_for match, url: tournament_match_path(@tournament, match), html: { id: "winGameForm" } do |f| %>
	      <%= f.fields_for :games, match.games.last do |builder| %>
	        <%= builder.hidden_field :winner_id, value: @waiting_player.id %>
	      <% end %>
	      <%= f.submit "Win Game", class: "actionButton activeAction" %>
	    <% end %>
	  <% elsif match.winner_id.nil? %>
	    <div class="actionButton disabledAction">Waiting For Other</div>
	  <% end %>
	<% else %>
	  <% if !player_relation.accepted %>
	    <%= form_for player_relation, url: tournament_match_match_player_relation_path(@tournament, match, player_relation), html: { id: "acceptMatchForm" } do |f| %>
	      <%= f.hidden_field :accepted, value: 1 %>
	      <%= f.submit "Accept Match", class: "actionButton activeAction" %>
	    <% end %>
	  <% end %>

	  <% if match.contested? && !player_relation.contested %>
	    <div class="actionButton disabledAction">A player has requested a moderator review.</div>
	  <% end %>
        <% end %>

	<% if player_relation.contested %>
	  <%= form_for player_relation, remote: true, url: tournament_match_match_player_relation_path(@tournament, match, player_relation, format: :json), html: { id: "callModForm" } do |f| %>
	    <%= f.hidden_field :contested, value: 0 %>
	    <%= f.submit "Dismiss Mod Call", class: "actionButton activeAction" %>
	  <% end %>
	<% else %>
	  <%= form_for player_relation, remote: true, url: tournament_match_match_player_relation_path(@tournament, match, player_relation, format: :json), html: { id: "callModForm" } do |f| %>
	    <%= f.hidden_field :contested, value: 1 %>
	    <%= f.submit "Call Mods", class: "actionButton activeAction" %>
	  <% end %>
	<% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tournaments/edit.html.erb
<% title "Edit Tournament" %>
<h1 id="tournamentHeader">Edit Tournament</h1>

<div id="editTournament">
  <%= render @tournament %>
</div>

app/views/tournaments/index.html.erb
<% title "Starcraft 2 Tournaments" %>
<h1 id="tournamentHeader">Tournament List</h1>

<% if can?(:create, Tournament) %>
  <div class="actionLinksContainer">
    <div class="actionLinks">
      <%= link_to "New Tournament", new_tournament_path if can?(:create, Tournament) %>
    </div>
  </div>
<% end %>

<div class="tournamentPanel" style="margin-top: 10px;">
  <h2>Tournaments Open to All</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::ALL %>
</div>

<div class="tournamentPanel">
  <h2>Grand Master Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::GRAND_MASTER %>
</div>

<div class="tournamentPanel">
  <h2>Master Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::MASTER %>
</div>

<div class="tournamentPanel">
  <h2>Diamond Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::DIAMOND %>
</div>

<div class="tournamentPanel">
  <h2>Platinum Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::PLATINUM %>
</div>

<div class="tournamentPanel">
  <h2>Gold Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::GOLD %>
</div>

<div class="tournamentPanel">
  <h2>Silver Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::SILVER %>
</div>

<div class="tournamentPanel">
  <h2>Bronze Tournaments</h2>
  <%= render "column_names" %>
  <%= render "league_index", league: Tournament::BRONZE %>
</div>

app/views/tournaments/new.html.erb
<% title "New Tournament" %>
<h1 id="tournamentHeader">New Tournament</h1>

<div id="newTournament">
  <%= render @tournament %>
</div>

app/views/tournaments/show.html.erb
<% title "Starcraft 2 Tournament - #{@tournament.name}" %>
<h1 id="tournamentHeader"><%= @tournament.name %></h1>

<% player = current_user_player || new_player(@tournament, current_user) %>

<% if (can?(:create, player) && player.new_record?) || (can?(:destroy, player) && !player.id.nil?) || can?(:update, @tournament) %>
  <div class="actionLinksContainer">
    <div class="actionLinks">
      <%= link_to "Join Tournament", tournament_waiting_players_path(@tournament), method: :post, waiting_player: player.to_json if can?(:create, player) && player.new_record? %>
      <%= link_to "Leave Tournament", tournament_waiting_player_path(@tournament, player), method: :delete, id: "leaveTournamentLink" if can?(:destroy, player) && !player.id.nil? %>
      <%= link_to "Edit Tournament", edit_tournament_path(@tournament) if can?(:update, @tournament) %>
    </div>
  </div>
<% end %>

<div class="inlineBlockContainer">
  <div id="tournamentQuickInfo">
    <h2>Quick Info</h2>
    <a href="javascript:void(0)" id="hideShowQuickInfo">Show</a>
    <div id="quickInfoContainer">
      <table>
	<tr><td style="text-align: center; padding-left: 0;">
	    <% leagues = Tournament::LEAGUES.keys %>
	    <% leagues.delete(Tournament::ALL) %>
	    <% leagues.each do |league| %>
	      <%= image_tag image_for_league(league) if @tournament.league & league > 0 %>
	    <% end %>
	</td></tr>
	<tr><td>
	    Starts In: <b><%= to_time_remaining @tournament.start_time %></b>
	</td></tr>
	<tr><td>
	    Spots Open: <b><%= @tournament.open_spots %></b>
	</td></tr>
	<tr><td style="border-bottom: 0;">
	    Prize Pool: <b>$<%= @tournament.prize %></b>
	</td></tr>
      </table>
    </div>
  </div>
  
  <div id="tournamentPlayerList">
    <h2>Player List</h2>
    <a href="javascript:void(0)" id="hideShowPlayerList">Show</a>
    <div id="playerListContainer">
      <table>
	<% player_count = 0 %>
	<% accepted_players = @tournament.waiting_players.where(player_accepted: true) %>
	<% accepted_players.each do |player| %>
	  <% if player_count % 5 == 0 %><tr><% end %>
          <% player_count += 1 %>
	  <% cell_class = player_count.even? ? "lightCell" : "darkCell" %>
          <td class="playerListEntry <%= cell_class %>"><%= player.user.login %></td>
	  <% if player_count % 5 == 0 %></tr><% end %>
	<% end %>
	<% if accepted_players.length % 5 != 0 && @tournament.open_spots == 0 %></tr><% end %>

	<% @tournament.open_spots.times do %>
	  <% if player_count % 5 == 0 %><tr><% end %>
          <% player_count += 1 %>
	  <% cell_class = "openSpot" %>
	  <% cell_class += player_count.even? ? " lightCell" : " darkCell" %>
          <td class="playerListEntry <%= cell_class %>">Open Spot</td>
	  <% if player_count % 5 == 0 %></tr><% end %>
        <% end %>
	<% if accepted_players.length % 5 != 0 %></tr><% end %>
      </table>

      <% waiting_list = @tournament.waiting_players.where(player_accepted: false) %>
      <% if !waiting_list.empty? %>
        <h3>Waiting List</h3>
        <table>
	 <% player_count = 0 %>
	 <% waiting_list.each do |waiter| %>
	   <% if player_count % 5 == 0 %><tr><% end %>
	   <% player_count += 1 %>
	   <% cell_class = player_count.even? ? "lightCell" : "darkCell" %>
	   <td class="waitingListEntry <%= cell_class %>"><%= waiter.user.login %></td>
	   <% if player_count % 5 == 0 %></tr><% end %>
	 <% end %>

	 <% remaining_cells = (5 - (player_count % 5)) % 5 %>
	 <% remaining_cells.times do %>
	   <% player_count += 1 %>
	   <% cell_class = player_count.even? ? "lightCell" : "darkCell" %>
	   <td class="waitingListEntry openSpot <%= cell_class %>">N/A</td>
	 <% end %>
	 <% if remaining_cells > 0 %></tr><% end %>
	</table>
      <% end %>
    </div>
  </div>
</div>

<% if @waiting_player %>
  <%= render "player_actions" %>
<% end %>

<% style = @tournament.started? ? "padding-bottom: 0px;" : "" %>
<div class="tournamentPanel" style="<%= style %>">
  <h2>Tournament Bracket</h2>

  <% if @tournament.started? %>
    <%= render "partial_bracket" %>
  <% else %>
    <div class="noTournamentsMessage">
      Brackets will be generated once the tournament starts.
    </div>
  <% end %>
</div>