config/routes.rb
CloudLeagues::Application.routes.draw do
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', as: :logout
  resource :password_resets, except: [:show]

  resources :users do
    resource :account_information, as: :profile, path: :profile
    resources :chat_messages, only: [:index, :show, :new, :create, :destroy]
  end

  resources :tournaments do
    resources :waiting_players, only: [:create, :update, :destroy], path: :players
    resources :matches, only: [:index, :show, :edit, :update] do
      resources :match_player_relations, only: [:update]
    end
  end

  resources :maps

  resources :feedbacks, only: [:create]

  root to: 'home#index'
end

app/helpers/shared_helper.rb
module SharedHelper
  def top_players(limit = 5)
    players = WaitingPlayer.joins('JOIN matches ON matches.winner_id = waiting_players.id').group('user_id').order("count_all DESC").limit(3).count
    players.delete(nil)

    players
  end

  def large_prize_tournaments(league = Tournament::ALL, limit = 3)
    Tournament.where('registration_time < ? AND start_time > ? AND league & ? > 0', Time.now, Time.now, league).order('prize DESC').limit(limit)
  end
end

app/views/shared/_additional_links.html.erb
<div id="additionalLinks">
  <div class="ribbonTitle">
    ADDITIONAL LINKS
  </div>

  <div class="ribbonFold">
    <%= image_tag "big_ribbon_fold.png" %>
  </div>
  
  <div class="sidebarLeft">
    <div id="additionalLinkList">
      <ul>
	<li><%= link_to "Map Database", maps_path %></li>
	<li><%= link_to "Cloud Blog", "http://blog.cloudleagues.com" %></li>
	<li><%= link_to "r/Starcraft", "http://reddit.com/r/starcraft" %></li>
	<li><%= link_to "Team Liquid", "http://www.teamliquid.net" %></li>
	<li><%= link_to "SC2 Casts", "http://www.sc2casts.com" %></li>
	<li><%= link_to "SC2 Daily", "http://www.sc2daily.com" %></li>
	<li><%= link_to "Well Played", "http://www.wellplayed.org", style: "border-bottom: 0;" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_big_prizes.html.erb
<div id="biggestPrizePools">
  <div class="ribbonTitle">
    LARGEST PRIZE POOLS
  </div>

  <div class="ribbonFold">
    <%= image_tag "big_ribbon_fold.png" %>
  </div>

  <div class="sidebarLeft">
    <div id="biggestPrizePoolsMenu">
      <a href="javascript:void(0)" title="Grand Master" id="gmTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::GRAND_MASTER) %>
      </a>
      
      <a href="javascript:void(0)" title="Master" id="masterTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::MASTER) %>
      </a>
      
      <a href="javascript:void(0)" title="Diamond" id="diamondTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::DIAMOND) %>
      </a>
      
      <a href="javascript:void(0)" title="Platinum" id="platinumTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::PLATINUM) %>
      </a>
      
      <a href="javascript:void(0)" title="Gold" id="goldTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::GOLD) %>
      </a>
      
      <a href="javascript:void(0)" title="Silver" id="silverTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::SILVER) %>
      </a>
      
      <a href="javascript:void(0)" title="Bronze" id="bronzeTab" class="biggestPrizePoolsTab">
	<%= image_tag image_for_league(Tournament::BRONZE) %>
      </a>
    </div>

    <div id="gmContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::GRAND_MASTER, limit: 5 %>
    </div>
    
    <div id="masterContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::MASTER, limit: 5 %>
    </div>
    
    <div id="diamondContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::DIAMOND, limit: 5 %>
    </div>
    
    <div id="platinumContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::PLATINUM, limit: 5 %>
    </div>
    
    <div id="goldContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::GOLD, limit: 5 %>
    </div>
    
    <div id="silverContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::SILVER, limit: 5 %>
    </div>
    
    <div id="bronzeContent" class="biggestPrizePoolsContent">
      <%= render "shared/big_prizes_for_league", league: Tournament::BRONZE, limit: 5 %>
    </div>
  </div>
</div>

app/views/shared/_big_prizes_for_league.html.erb
<%
   "league ||= Tournament::ALL"
   "limit ||= 5"
   tournaments = large_prize_tournaments(league, limit)
%>

<% tournaments.each do |tournament| %>
  <div class="largePrizeRow">
    <%= link_to tournament.name, tournament_path(tournament) %>
    <div class="largePrizeTournamentInfo">
      Prize: $<%= tournament.prize %> | 
      Open Spots: <%= tournament.open_spots %> |
      Starts In: <%= to_time_remaining tournament.start_time %>
    </div>
  </div>
<% end %>

<% (limit - tournaments.size).times do %>
  <div class="largePrizeRow noLargePrizeToDisplay">
    <p>There is no tournament to display.</p>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<%
  # This partial view displays error messages for a form. The object used in
  # the form is passed as a target.
%>

<% if target.errors.any? %>
  <div id="errorExplanation">
    <h2>There were <%= pluralize(target.errors.count, "error") %>.</h2>
    
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feedback.html.erb
<div id="feedback">
  <div id="showFeedbackForm">Submit Feedback</div>

  <div id="feedbackFormContainer">
    <div id="feedbackErrors"></div>

    <% feedback = Feedback.new %>
    <% feedback.user_id = current_user.id unless current_user.nil? %>
    <%= form_for feedback, remote: true, url: feedbacks_path(format: :json),html: { id: "feedbackForm" } do |form| %>
      <fieldset>
	<%= form.hidden_field :user_id %>

	<table>
	  <tr>
	    <td><%= form.select :category, Feedback::CATEGORIES.map { |key, val| [val, key] }, { include_blank: 'Select Category'} %></td>
	  </tr>
	  
	  <tr>
	    <td><%= form.text_area :message, size: "25x10" %></td>
	  </tr>
	  
	  <tr><td>
	      <div style="vertical-align: top;">
		<div style="display: inline-block; vertical-align: top;">
		  <%= form.submit "Submit", id: "feedbackSubmit" %>
		</div>

		<div id="feedbackLoader">
		  <%= image_tag "loader.gif" %>
		</div>
	      </div>
	  </td></tr>
	</table>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
Copyright &copy; 2012 Cloud Leagues. All Rights Reserved.

app/views/shared/_leaderboard.html.erb
<div id="leaderboard">
  <div class="ribbonTitle">
    LEADERBOARDS
  </div>

  <div class="ribbonFold">
    <%= image_tag "big_ribbon_fold.png" %>
  </div>
  
  <div class="sidebarLeft">
    <% if top_players.empty? %>
      <div id="noTopPlayers">
	There are no top players to display.
      </div>
    <% else %>
      <div id="topPlayers">
	<% top_players.each do |player_id| %>
	  <% user = User.find_by_id(player_id) %>
	  <div class="topPlayerRow">
	    <div class="userPortrait">
	      <%= image_tag user.avatar_url %>
	    </div>
	    <div class="leaderboardUserInfo">
	      <% win_loss_array = user.win_loss_array %>
	      <%= link_to user.login, user_path(user) %>
	      <div class="leaderboardUserStats">
		Wins - <%= win_loss_array[0] %> |
		Losses - <%= win_loss_array[1] %>
	      </div>
	    </div>
	  </div>
	<% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebarContent">
  <%= render "shared/leaderboard", top_players: top_players(4) %>
  <%= render "shared/big_prizes" %>
  <%= render "shared/additional_links" %>
</div>

app/views/shared/_site_navigation.html.erb
<div id="siteNavigation">
  <div class="navButtons">
    <div class="button_outer first_button">
      <%= link_to "Home", root_path, class: "button_inner" %>
    </div>

    <div class="button_outer">
      <%= link_to "Tournaments", tournaments_path, class: "button_inner" %>
    </div>

    <div class="button_outer last_button">
      <%= link_to "Users", users_path, class: "button_inner" %>
    </div>
  </div>
</div>

<div id="headerLogo">
  <%= link_to image_tag("header_logo.png", alt: "Cloud Leagues"), root_path %>
</div>

<%= content_for?(:user_navigation) ? yield(:user_navigation) : render("shared/user_navigation") %>

app/views/shared/_user_navigation.html.erb
<div id="userNavigation">
  <div class="userPane">
    <div class="userPortrait">
      <%= image_tag current_user.avatar_url unless current_user.nil? %>
    </div>

    <ul class="userInformation">
      <li>
	Welcome <b><%= current_user ? current_user.login : "Guest" %></b>
      </li>
      
      <li>
	<% if current_user %>
	  <% win_loss_array = current_user.win_loss_array %>
	  Wins: <%= win_loss_array[0] %> | Losses: <%= win_loss_array[1] %>
	<% else %>
	  Login to view record.
	<% end %>
      </li>
    </ul>

    <% if current_user %>
      <div class="button_outer">
	<%= link_to "Your Profile", user_profile_path(current_user), class: "button_inner" %>
      </div>

      <div class="button_outer last_button">
	<% chat_id = current_user.chat_profile.nil? ? nil : current_user.chat_profile.chat_id %>
	<% unread_messages = ChatMessage.where(recipient_id: chat_id, read: false) %>
	<% menu_class = unread_messages.empty? ? "" : "displayMessageIcon" %>
	<dl class="dropMenu <%= menu_class %>", id="dropMenuArrow">
	  <dt>
	    <%= link_to "", "javascript:void(0)", class: "button_inner", id: "linkglobal"  %>
	  </dt>
	  <dd>
	    <ul id="ulglobal">
	      <li style="margin-top: 2px;"><%= link_to "Messages", user_chat_messages_path(current_user), id: "linkToChatMessages" %></li>
	      <li><%= link_to "Logout", logout_path, method: :delete %></li>
	    </ul>
	  </dd>
	</dl>
      </div>
 
    <% else %>
      <div class="button_outer">
	<%= link_to "Login", login_path, class: "button_inner" %>
      </div>

      <div class="button_outer last_button">
	<%= link_to "Register", new_user_path, class: "button_inner" %>
      </div>
    <% end %>
  </div>
</div>