config/routes.rb
CloudLeagues::Application.routes.draw do
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', as: :logout
  resource :password_resets, except: [:show]

  resources :users do
    resource :account_information, as: :profile, path: :profile
    resources :chat_messages, only: [:index, :show, :new, :create, :destroy]
  end

  resources :tournaments do
    resources :waiting_players, only: [:create, :update, :destroy], path: :players
    resources :matches, only: [:index, :show, :edit, :update] do
      resources :match_player_relations, only: [:update]
    end
  end

  resources :maps

  resources :feedbacks, only: [:create]

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
    if current_user && !current_user.chat_profile.nil?
      chat_id = current_user.chat_profile.chat_id
      recent_messages = Hash[ChatMessage.where(recipient_id: chat_id).group(:sender_id).maximum("id").sort.reverse]
      @recent_messages = []
      
      for i in 0..4
        if !recent_messages.keys[i].nil?
          key = recent_messages.keys[i]
          message = ChatMessage.find_by_id(recent_messages[key])
          chat_profile = ChatProfile.find_by_chat_id(key)
          user = chat_profile.nil? ? nil : chat_profile.user

          @recent_messages.push [user, message]
        end
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def tournaments_for_current_user
    all_tournaments = Tournament.where 'league = :league OR league = #{Tournament::ALL} AND registration_time < #{Time.now} AND start_time > #{Time.now}', league: current_user.account_information.league
  end
end

app/views/home/_guest_welcome.html.erb
<h1 id="homeWelcome">Welcome to Cloud Leagues</h1>

<div class="homePanel">
  <h2>What is Cloud Leagues?</h2>
  <p>
    <b>Cloud Leagues</b> is a free online service that allows you to play Starcraft online for fame, and sometimes fortunes. There are tournaments hosted at regular intervals, so you can always participate in a competetive Starcraft experience. 
  </p>
</div>
  
<div class="homePanel">
  <h2>How do you participate?</h2>
  <p>
    Participation is easy. Simply click the link in the top right to register an account. Once you do that, fill in your Starcraft account information, including your Username, Character Code, and Race. Then, you can browse the active tournaments, and find one that accomidates your time frame and play level.
  </p>
</div>

<div class="homePanel">
  <h2>Can I create my own tournament?</h2>
  <p>
    Right now, no. Sorry, but it's a lot of work programming all of these features! Currently, the team only consists of one person, but I have the programming power of at least 20 people my size. Check back regularly for updates. Some things to look forward to:
    <ul>
      <li>Create your own tournaments.</li>
      <li>Participate in a custom league</li>
      <li>Create your own private league, to create a competitive place for you and your friends.</li>
    </ul>
  </p>
</div>

app/views/home/_user_welcome.html.erb
<h1 id="homeWelcome">Welcome Home</h1>

<div class="homePanel" id="featureSpotlight">
  <h2>Feature Spotlight</h2>
  <div id="spotlightExplanation">
    <h3><a href="http://blog.cloudleagues.com">The Cloud Leagues Blog</a></h3>
    <p>Introducing the <a href="http://blog.cloudleagues.com">Cloud Leagues Blog</a>! I will be posting information about upcoming features as they come under development. You can post comments with your feedback, and I may incorporate your ideas into the site. I will also be posing a good number of Ruby on Rails information, so check those out if web development interests you.</p>
  </div>
</div>


<% if current_user.account_information.nil? %>
  <div class="homePanel" id="accountInfoNotice">
    <h2>Hey! This is important.</h2>
    <p style="margin-bottom: 0;">We noticed that we haven't set up a profile yet. In order to use many of the features on this site, you must provide some information about yourself. Don't worry, this isn't as stressful as a police interrogation, but you will need to provide a Starcraft 2 username and character code. If you don't have one, that's OK, you can still look. Here are some great things you can do by creating a profile:</p>
    
    <ul>
      <li>Join Tournaments</li>
      <li>Access Replays</li>
      <li>Utilize Our Chat System</li>
    </ul>
    
    <p>
      We hope you will join us. <%= link_to "Click here to create a new profile.", new_user_profile_path(current_user) %>
    </p>
  </div>

  <div class="homePanel">
    <h2>Tournament Information</h2>
    <p>Please <%= link_to "create a profile", new_user_profile_path(current_user) %> to view tournament information tailored to you.</p>
  </div>
<% else %>
  <div class="messagePanel", style="padding-bottom: 0;">
    <h2>Your Recent Messages</h2>
    
    <% @recent_messages.each do |sender, message| %>
      <div class="messagePreviewContainer<%= message.read ? "" : " newMessage" %>">
	<div class="userPortrait">
	  <%= image_tag sender.avatar_url unless sender.nil? %>
	</div>
	
	<div class="messagePreview">
	  <% user = sender.nil? ? "Unkown User" : sender.login %>
	  <p class="messageSender"><%= link_to user, user_chat_message_path(current_user, message) %></p>

	  <% text = message.message.length > 50 ? message.message[0, 50] + "..." : message.message %>
	  <p class="messageText"><%= text %></p>
	</div>
      </div>
    <% end %>
  </div>

  <div class="tournamentPanel">
    <h2>Open Tournaments for You</h2>
    <%= render "tournaments/column_names" %>
    <%= render "tournaments/league_index", league: current_user.account_information.league %>
  </div>

  <div class="tournamentPanel">
    <h2>Recent High Level Tournaments</h2>
    <% league = Tournament::GRAND_MASTER | Tournament::MASTER %>
    <%= render "tournaments/column_names" %>
    <%= render "tournaments/league_index", league: league %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if current_user %>
  <%= render "user_welcome" %>
<% else %>
  <%= render "guest_welcome" %>
<% end %>