config/routes.rb
CloudLeagues::Application.routes.draw do
  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', as: :logout
  resource :password_resets, except: [:show]

  resources :users do
    resource :account_information, as: :profile, path: :profile
    resources :chat_messages, only: [:index, :show, :new, :create, :destroy]
  end

  resources :tournaments do
    resources :waiting_players, only: [:create, :update, :destroy], path: :players
    resources :matches, only: [:index, :show, :edit, :update] do
      resources :match_player_relations, only: [:update]
    end
  end

  resources :maps

  resources :feedbacks, only: [:create]

  root to: 'home#index'
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  # Validations
  validates :sender_id, :presence => true
  validates :recipient_id, :presence => true
  validates :message, :presence => true

  # Callbacks
  before_validation :strip_inputs

  protected
  def strip_inputs
    message.strip! if message
  end
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  before_filter :authenticate
  load_and_authorize_resource

  def index
    chat_id = current_user.chat_profile.chat_id
    new_messages = Hash[ChatMessage.where(recipient_id: chat_id).group(:sender_id).maximum("id").sort.reverse]
    @messages = []

    new_messages.each do |key, val|
      chat_profile = ChatProfile.find_by_chat_id(key)
      message = ChatMessage.find_by_id(val)
      user = chat_profile.nil? ? nil : chat_profile.user

      @messages.push [user, message]
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: { unread_messages: !ChatMessage.where(recipient_id: chat_id, read: false).empty? }.to_json }
    end
  end

  def show
    @message = @chat_message
    sender = @message.sender_id == current_user.chat_profile.chat_id ? @message.recipient_id : @message.sender_id
    recipient = @message.recipient_id == current_user.chat_profile.chat_id ? @message.recipient_id : @message.sender_id

    @messages = ChatMessage.where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', sender, recipient, recipient, sender).order('id DESC').limit(100)
    @sender = ChatProfile.find_by_chat_id(sender).user rescue nil

    render

    @messages.each { |message| message.update_column :read, true if @message.recipient_id == current_user.chat_profile.chat_id }
  end

  def new
    @message = ChatMessage.new
    @message.sender_id = current_user.chat_profile.chat_id
  end

  def create
    if params[:chat_message] && params[:chat_message][:recipient_id]
      profile = ChatProfile.find_by_chat_id params[:chat_message][:recipient_id]

      if profile.nil?
        user = User.find_by_login params[:chat_message][:recipient_id]
        params[:chat_message][:recipient_id] = user.chat_profile.chat_id unless user.nil? || user.chat_profile.nil?
        params[:chat_message][:recipient_id] = nil if user.nil? || user.chat_profile.nil?
      end
    end
    
    @message = ChatMessage.new params[:chat_message]
 
    if @message.save
      flash[:notice] = 'Message sent.'
      redirect_to user_chat_message_path(current_user, @message)
    else
      flash[:notice] = 'Message could not be sent.'
      render action: :new
    end
  end

  def destroy
    @chat_message.destroy
    flash[:notice] = 'Message destroyed.'
    redirect_to user_chat_messages_path(current_user)
  end
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/views/chat_messages/_chat_message.html.erb
<%= form_for [current_user, @message] do |form| %>
  <fieldset>
    <%= form.hidden_field :sender_id %>	
    <table>
      <tr>
	<td><%= form.label :recipient_id, "To" %></td>
	<td><%= form.text_field :recipient_id %></td>
      </tr>
      
      <tr>
	<td style="vertical-align: top; padding-right: 5px;"><%= form.label :message, "Message" %></td>
	<td><%= form.text_area :message, size: "60x5" %></td>
      </tr>

      <tr><td></td><td><%= form.submit "Send", id: "submitButton" %></td></tr>
    </table>        
  </fieldset>
<% end %>

app/views/chat_messages/index.html.erb
<% title "Your Messages" %>
<h1 id="messageHeader">Your Messages</h1>

<div class="actionLinksContainer">
  <div class="actionLinks">
    <%= link_to "New Message", new_user_chat_message_path(current_user) %>
  </div>
</div>

<div class="messagePanel" style="margin-top: 10px; padding-bottom: 0;">
  <h2>Current Conversations</h2>

  <div id="refreshMessageIndex"><%= link_to "You have unread messages. Click here to see them.", user_chat_messages_path(current_user) %></div>

  <% @messages.each do |sender, message| %>
    <div class="messagePreviewContainer<%= message.read ? "" : " newMessage" %>">
      <div class="userPortrait">
	<%= image_tag sender.avatar_url unless sender.nil? %>
      </div>

      <div class="messagePreview">
	<% user = sender.nil? ? "Unknown User" : sender.login %>
	<p class="messageSender"><%= link_to user, user_chat_message_path(current_user, message) %></p>
	
	<% text = message.message.length > 50 ? message.message[0, 50] + "..." : message.message %>
	<p class="messageText"><%= text %></p>
      </div>
    </div>
  <% end %>

  <% if @messages.empty? %>
    <p class="noMessages">You have no messages to display.</p>
  <% end %>
</div>

app/views/chat_messages/new.html.erb
<h1 id="messageHeader">New Message</h1>

<div class="messagePanel">
  <h2>Compose Message</h2>

  <div style="padding-left: 15px;"><%= render @message %></div>
</div>

app/views/chat_messages/show.html.erb
<% user = @sender.nil? ? "Unkown User" : @sender.login %>
<% title "Conversation with #{user}" %>
<h1 id="messageHeader">Your Messages</h1>

<div class="messagePanel" style="padding-bottom: 0;">
  <h2>Conversation with <%= user %></h2>

  <div class="sendMessage">
    <% if !@sender.nil? %>
      <h2>Send Message</h2>
      <% @message = ChatMessage.new sender_id: current_user.chat_profile.chat_id, recipient_id: @sender.login %>
      <%= render @message %>
    <% end %>
  </div>

  <% first = true %>
  <% @messages.each do |message| %>
    <div class="messagePreviewContainer <%= message.read ? "" : " newMessage" %>">
      <div class="userPortrait">
	<% if message.sender_id == current_user.chat_profile.chat_id %>
	  <%= image_tag current_user.avatar_url %>
	<% else %>
	  <%= image_tag @sender.avatar_url unless @sender.nil? %>
	<% end %>
      </div>

      <div class="messagePreview">
	<% if message.sender_id == current_user.chat_profile.chat_id %>
	  <p class="messageSender"><%= current_user.login %></p>
	<% else %>
	  <p class="messageSender"><%= link_to_if !@sender.nil?, user, user_profile_path(@sender) %></p>
	<% end %>

	<p class="messageDate">Sent on <%= message.created_at.to_date %> <%= "(Latest)" if first %></p>

	<p class="messageText"><%= message.message %></p>
      </div>
    </div>
    <% first = false %>
  <% end %>
</div>